### ISSUE TITLE
[Issues/To-Do List] Bot3 [S/E: 26/04/2021]

### ISSUE THREAD

**Issue by yiesko** [TrebleExperience/Bot3#6]
### Problems that must be solved before v1.0.1 release
- [X] `configs.prop` problem at the first start of the bot (https://github.com/TrebleExperience/Bot3/commit/fee9cbdc58d6181b2480d5f065edaeb76656d2a0)
- [X] `allowed2port.json` spam in console/terminal when it doesn't exist (https://github.com/TrebleExperience/Bot3/commit/27b14f286d3fe64dd86acf6a13d8832091cb1dac)

### Suggestions to be made
- [X] Redo some parts of the `ErfanGSIs` class (https://github.com/TrebleExperience/Bot3/commit/8756ac2aa0e9e41561c46c4adb3d3e32085136bc, https://github.com/TrebleExperience/Bot3/commit/6a0d09e01244114c2bdc2b39148225df8b1dff43 & https://github.com/TrebleExperience/Bot3/commit/640b1c91354686ce771c9ae736734c52a9f80a32) [3/3]
- [X] Fix outdated link for About command (https://github.com/TrebleExperience/Bot3/commit/712e0433f8162ac307bc9af3a0c9d47535f09fa6)
- [ ] Add [sGSI](https://github.com/xiaoxindada/SGSI-build-tool) support (It is not planned to do or add quickly now, perhaps this requires attention from the main maintainer of the tool)
- [X] Use `PrefObj` to get strings from the EN and BR languages ​​in remaining classes (https://github.com/TrebleExperience/Bot3/commit/d1595587e477e930f5fab46af17b6378969b5016)

### Observation
* `S` in issue title: 'Start of:'
* `E` in issue title: 'Ended on:'

**Comment by yiesko** [comment]
Done, in relation to `sGSI`: When I have enough time to do this, I will try to bring it to the source, help is welcome, especially from the maintainer of the tool.
